name: GitBook Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 10
        uses: actions/setup-node@v3
        with:
          node-version: '10'

      - name: Install gitbook-cli globally
        run: npm install -g gitbook-cli

      - name: Install project dependencies
        run: npm install

      - name: Fix audit vulnerabilities (optional)
        run: npm audit fix

      - name: Build GitBook
        run: gitbook build